### ISSUE TITLE
Removing error from binary search code.

### ISSUE THREAD

**Issue by CoderAayush2104** [wingkwong/leetcode-the-hard-way#230]
The code written there might get an error(StackOverflow) . I will correct it for you

**Comment by wingkwong** [comment]
???

**Comment by CoderAayush2104** [comment]
I will correct the stack overflow error for you.I will do it for sure

**Comment by CoderAayush2104** [comment]
when you do start + end for large numbers there will be stack overflow error.Please assign this to me . I will fix it for you.

**Comment by wingkwong** [comment]
Can you point out which line has the problem in the code? and also which file are you talking about?

**Comment by CoderAayush2104** [comment]
int mid = (s + e) /2

**Comment by wingkwong** [comment]
Which file ...

**Comment by CoderAayush2104** [comment]
binary search in basic concepts in tutorial

**Comment by wingkwong** [comment]
Closing this PR.

1. This issue is very unclean. After a few days, I still have no idea what it is.
2. I believe you meant integer overflow instead of stackoverflow
3. I couldn't see `int mid = (s + e) /2`. If you mean `mid = (lp + rp) // 2`, then it's fine because it is written in python. I've already mentioned l + (r - l) / 2 in tips.
