### ISSUE TITLE
Tutorial writeup - LCA

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#241]
For those who wanna take it, please state 2 - 3 LC problems that you're gonna use for this writeup. Prefer someone who has deep knowledge on this topic.

**Comment by M-Rahul1** [comment]
Can i take up this?

**Comment by wingkwong** [comment]
@M-Rahul1 Sorry. No due to your plagiarism record.

**Comment by aayushi02agarwal** [comment]
I want to work on this issue, please assign to me. I can use the following hard problems of LC:
Prob. no. 87) Scramble string
Prob. no. 123)  Best Time to Buy and Sell Stock III
Prob. no. 239) Sliding Window Maximum

Please assign it to me under Hacktoberfest2022 label.

**Comment by wingkwong** [comment]
@aayushi02agarwal Just went through the problems. It seems that those 3 problems are not related to LCA. Can you share your submission links to prove that you've solved them with LCA?

**Comment by aayushi02agarwal** [comment]
Oh I'm so sorry, I read the topic wrong. I don't have a deep understanding on this.

**Comment by RohitTaparia** [comment]
I want to work on this issue, since I have a good understanding of LCA and have worked on problems related to it.
The problems can be:
1) finding LCA of a binary tree- This has 4 parts on LC , and I can explain them.
Hence, I can also explain the different approaches of finding LCA with different time complexities.
2) Step-By-Step Directions From a Binary Tree Node to Another-[Link](https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/)

**Comment by wingkwong** [comment]
@RohitTaparia Assigned. Before starting to work, please read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) as well as the existing PR comments to avoid some common mistakes.
