### ISSUE TITLE
Tutorial Writeup - Kahn's Algorithm

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#64]
Markdown Path: `tutorials/graph-theory/kahns-algorithm.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by i-dipanshu** [comment]
Hey @wingkwong 
I'd like to document this algorithm
Could you assign this task to me

**Comment by wingkwong** [comment]
Unassigned as requested. If anyone wants to pick up, please leave a comment here.

**Comment by AyushK-101** [comment]
I would like to work on this issue

**Comment by parth-verma7** [comment]
Hi @wingkwong I would like to work on this issue. Can you please assign it to me?

**Comment by wingkwong** [comment]
I'll let @AyushK-101 take it given no task is assigned to AyushK.

**Comment by divya16-bit** [comment]
@wingkwong , I am so sorry to start working on this task before asking it out here and getting it assigned to me but since it's been 8 days of assigning this issue and it was not completed , I thought that now i'll be eligible to work on this task.
But now, I would like this issue to be assigned it me and i will also work on  the requested changes.

**Comment by AyushK-101** [comment]
I think it would be best if someone else takes up this issue, I will be busy for a few days, @divya16-bit you might work on the issue if that's okay with @wingkwong

**Comment by wingkwong** [comment]
@AyushK-101 Thanks for the confirmation. @divya16-bit You'll take it up.

**Comment by wingkwong** [comment]
5261f3264acd4179a8b63c39285d71492b832d30
